theme = "hugo-theme-learn"
baseURL = "/"
languageCode = "en-us"
title = "Data Science Course in a Box"
publishDir = "docs"
relativeurls = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"